version: '3.8'
services:

  redis:
    image: redis:latest
    container_name: redis
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    restart: always
    networks:
      - task-tracker-network

networks:
  task-tracker-network:
    external: true